version: 2.1
jobs:
  build:
    docker:
      - image: nixos/nix:2.3
    steps:
      - checkout
      - run:
          name: "Build"
          command: nix-build --pure release.nix
  build_dashboard:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "./dashboard/package.json" }}
      - run:
          name: "Install dependencies"
          command: cd dashboard && npm install
      - save_cache:
          key: dependency-cache-{{ checksum "./dashboard/package.json" }}
          paths:
            - ./dashboard/node_modules
      - run:
          name: "Build"
          command: cd dashboard && npm run prod

workflows:
  version: 2
  build_all:
    jobs:
      - build
      - build_dashboard
