version: 2.1
jobs:
  build:
    docker:
      - image: nixos/nix:2.3
    steps:
      - checkout
      - run:
          name: "Build"
          command: nix-build --pure release.nix
  build_dashboard:
    working_directory: "~/project/dashboard"
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: "Install YARN"
          command: "sudo npm install yarn"
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn-lock.json" }}
      - run:
          name: "Install dependencies"
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: "Build"
          command: npm run prod

workflows:
  version: 2
  build_all:
    jobs:
      - build
      - build_dashboard
